#include <stdint.h>

#ifndef VIDEO_RESOLUTIONS_H
#define VIDEO_RESOLUTIONS_H

#define W_MAX_RESOLUTION_PIXELS UINT64_C(2048) //Change  back to 65535UL when needed.
#define W_MIN_RESOLUTION_PIXELS UINT64_C(2)

#define H_MAX_RESOLUTION_PIXELS UINT64_C(65536)
#define H_MIN_RESOLUTION_PIXELS UINT64_C(2)

#endif