

#ifndef VIDEO_RESOLUTIONS_H
#define VIDEO_RESOLUTIONS_H

#define W_MAX_RESOLUTION_PIXELS 2048UL //Change  back to 65535UL when needed.
#define W_MIN_RESOLUTION_PIXELS 2UL

#define H_MAX_RESOLUTION_PIXELS 65536UL
#define H_MIN_RESOLUTION_PIXELS 2UL

#endif